version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  sample:  # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run. 
    # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows 
    jobs:
      - build-and-test


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - python/install-packages:
          pkg-manager: pip
          name: Run tests
          command: pytest
      - run:
          name: Build docker image
          command: docker build -t kaggle_M5_aggregations . 
      - run:
          name: Run tests inside docker container
          command: docker run -it kaggle_M5_aggregations pytest
